# Generated by Django 5.2.7 on 2025-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=10)),
                ('st_name', models.CharField(max_length=30)),
                ('st_age', models.IntegerField()),
            ],
        ),
    ]
