# Generated by Django 5.2.7 on 2025-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_salary', models.FloatField()),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
